#:import C models.theme

<CatalogScreen>:
    md_bg_color: C.BG

    MDBoxLayout:
        orientation: "vertical"

        FloatLayout:
            size_hint_y: None
            height: "160dp"

            Image:
                source: "img/bg2(1).jpg"
                fit_mode: "cover"
                size_hint: 1, 1
                pos_hint: {"x": 0, "y": 0}

            MDTextField:
                id: search_field
                mode: "filled"
                radius: [dp(0)]
                size_hint_x: 0.92
                size_hint_y: None
                height: "48dp"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                theme_bg_color: "Custom"
                fill_color_normal: 0, 0, 0, 0
                fill_color_focus: 0, 0, 0, 0
                theme_line_color: "Custom"
                line_color_normal: 1, 1, 1, 0.7
                line_color_focus: 1, 1, 1, 1
                theme_text_color: "Custom"
                text_color_normal: 1, 1, 1, 1
                text_color_focus: 1, 1, 1, 1
                on_text: root.on_search(self.text)

                MDTextFieldLeadingIcon:
                    icon: "magnify"
                    theme_icon_color: "Custom"
                    icon_color_normal: 1, 1, 1, 1
                    icon_color_focus: 1, 1, 1, 1

                MDTextFieldHintText:
                    text: "Поиск по препаратам..."
                    theme_text_color: "Custom"
                    text_color_normal: 1, 1, 1, 0.85
                    text_color_focus: 1, 1, 1, 0.6

        ScrollView:
            size_hint_y: 1.0
            do_scroll_x: False

            MDGridLayout:
                id: drug_grid
                cols: 2
                spacing: "12dp"
                padding: "12dp"
                adaptive_height: True
                size_hint_y: None
                height: self.minimum_height