#:import my_hex kivy.utils.get_color_from_hex
<ProfileScreen>:
    md_bg_color: my_hex('#ffffff')

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(10), dp(20), dp(10), dp(70)
        spacing: dp(10)

        MDLabel:
            text: 'Профиль владельца'
            halign: 'center'
            font_style: "Headline"
            role: "medium"
            adaptive_height: True

        ScrollView:
            do_scroll_x: False

            MDBoxLayout:
                id: cards_box
                orientation: 'vertical'
                adaptive_height: True
                spacing: dp(10)

    MDFabButton:
        icon: "plus"
        style: "standard"
        pos_hint: {"right": 0.95, "y": 0.05}
        on_release: root.manager.current = 'pet_form'